### ISSUE TITLE
Template update for new reallocated value scale

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#11]
The critical threshold for reallocated sectors is set to a min value of 0 - which would mean they were all reallocated on the new scale. Thinking it makes sense to set an error threshold for anything below 100% and critical for anything below 99.9 (since you're either on tiny media, giant sector sizes, or proper ... at that point).

**Comment by daviswr** [comment]
The reallocation threshold uses the raw number for 'Reallocated Sector Ct' in (ATA?) attributes, or 'Number of Reallocated Logical Sectors' in ATA device stats, or 'Elements in grown defect list' in SCSI output, depending on what's available. The same number you'll see in the Reallocated Sector Count graph. Based on our earlier conversations, it seemed like the most accurate way to know when things are starting to go wrong.

Only the Health Score graph uses the normalized (or calculated, in some cases) health % values. Right now, the only thresholds checked on those are what the drive provides.

**Comment by sempervictus** [comment]
Removal and installation of the zenpack seems to have cleaned this up too - it should be all set for production users
