### ISSUE TITLE
Duplicate Reallocation Events

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#14]
It looks like there is some inconsistency in how online/offline reallocations are reported. Here's a view from 3 hosts where 1 has two disks with problems, and one reports the same problem twice for the same disk in online/offline counters. Not sure what that's all about, but the `-iAH` output only shows reallocations, not whether they're on/offline which i'm thinking is the only thing we really care about: the total count. Question is though, do we want an average of the two if they both report, compare them and null-out the offlines if they are the same, or do something more clever entirely?
![image](https://user-images.githubusercontent.com/1331084/143689725-66ddb35e-e636-4615-9a63-3c7746528011.png)

**Comment by daviswr** [comment]
Looks like I'm storing the wrong value for offline count. It's supposed to come from attribute 198 but the parser is using attribute 5 instead, oops.. https://github.com/daviswr/ZenPacks.daviswr.SMART/blob/2facb6aa21a23bc04c93705e3691b72a234f1b1b/ZenPacks/daviswr/SMART/parsers/smartctl.py#L289-L292

Just a moment...

**Comment by daviswr** [comment]
Alright... try out 98a2989f9f2446f7aa1656b5f89acc52130f2158 ?

https://github.com/daviswr/ZenPacks.daviswr.SMART/blob/98a2989f9f2446f7aa1656b5f89acc52130f2158/ZenPacks/daviswr/SMART/parsers/smartctl.py#L289-L292

**Comment by sempervictus** [comment]
Looks like that's fixed, thank you.
