### ISSUE TITLE
Health check notifications stopped

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#16]
I've a few systems here which have the evil 4K series Intel SSDs (the ones where firmware went nuts at some number of idle hours and merc'd the drive due to an overflow in the firmware) - their firmware was updated soon as the flaw was identified, but they did log a bunch of errors on the old FW before ending up where they are now. They semi-legitimately fail health check (on paper anyway), but those alerts stopped after i reinstalled the zenpack today. Is there a property/template threshold i need to set somewhere like the reallocation count one, or is this a regression?

**Comment by daviswr** [comment]
That's odd. Hmm. Do you still have one of the health check failure events in history? Would like to see what it was throwing, if you could also post output of `smartctl -iHA -l devstat -l ssd -q noserial` with the drive from the event.

**Comment by sempervictus** [comment]
I think this was related to the weird installation issue - seems to be resolved now. Thanks
