### ISSUE TITLE
Feature Request: New Event for Updated Reallocation Count

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#17]
When dealing with a large number of disks, replacements often have to be scheduled for some future time provided that the reallocation count is reasonably low. Its still a critical event, but an acknowledged one from a workflow perspective. However, if the reallocations climb on an ack'd event, it does not become a new event again - stays in the ack'd state despite now being worse than before from the "operational concern" viewpoint (effectively mandating that ops folks revisit the problem, potentially reschedule for "closer to right _now_," etc).
Is this even possible with the Zenoss event system? Creating thresholds for each sector gone south seems fraught while tiering them seems imprecise.

**Comment by daviswr** [comment]
Might be possible to set a custom dedupe ID on the realloc events. I'll investigate

**Comment by daviswr** [comment]
Give 0a03100fd767731df1d78d9064ae9889831d1b2c a try?

**Comment by sempervictus** [comment]
Neat, thank you. Will build that out some time this evening and deploy on the v6 instance.
