### ISSUE TITLE
zSmartDiskMapMatch value

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#2]
I've tried setting `zSmartDiskMapMatch` to `sd*` and `/dev/sd*` to no avail (system has a few dozen drives, so goes into the `sdaa` name scheme).
What is this option expecting for path and pattern?

**Comment by daviswr** [comment]
The idea was to be similar to the stock `zHardDiskMapMatch` zProperty, so a regex, but if it's not set no filtering should occur and all discovered storage devices will be modeled.
Another thing that I'll put in the readme...

**Comment by sempervictus** [comment]
Thank you,, will try that next.
