### ISSUE TITLE
TALES error

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#6]
This is horribly non-descript, and sourced at `localhost` in the event, not the actual device (which _is_ recorded, as an IP, not the title):
```
resolution | Could  not create a command to send to zencommand because TALES evaluation  failed.  The most likely cause is unescaped special characters in the  command. eg $ or %
-- | --
tb_exception | 'DevicePath'
template | SMART
```
It's a Lenovo tower, no magical/stupid RAID nonsense (direct `smartctl` access to devices), does have a weird mix of drives in it

**Comment by sempervictus** [comment]
Very weird, on a target host (of an old zenoss 4.2.5 monitor) which has neither ZFS nor SMART monitoring enabled, a manual model run threw this gem @ me:
```python
Traceback (most recent call last):
File "/opt/zenoss/packs/ZenPacks.daviswr.ZFS/ZenPacks/daviswr/ZFS/__init__.py", line 55, in __init__
command = talesEvalStr(plugin.command, device)
File "/opt/zenoss/Products/ZenUtils/ZenTales.py", line 29, in talesEvalStr
return talesEval('string:%s' % expression, context, extra)
File "/opt/zenoss/Products/ZenUtils/ZenTales.py", line 55, in talesEval
raise InvalidTalesException(msg)
InvalidTalesException: Error when processing tales expression string:export PATH=$PATH:/sbin:/usr/sbin; if which ifconfig >/dev/null 2>&1; then ifconfig -a; elif which ip >/dev/null 2>&1; then echo "### ip addr output"; ip addr; else echo "No ifconfig or ip utilities were found."; exit 127; fi && echo __COMMAND__ && /bin/dmesg && echo __COMMAND__ && for path in /sys/class/net/*; do [ -d "${path}" ] || continue; dirname="$(basename "${path}")"; cat ${path}/speed > /dev/null 2>&1; if [[ 0 == $? ]] ; then echo ${dirname}:$(cat ${path}/speed); fi; done on context <Products.DataCollector.DeviceProxy.DeviceProxy instance at 0x863f998> : Exception Class <type 'exceptions.KeyError'> Message: 'PATH' 
```

**Comment by daviswr** [comment]
Have some ideas on the DevicePath attribute not being populated for a component on the model, and will investigate while overhauling the whole path/title/id situation for RAID.

For the second one, the old 4.2.5 box, it seems like an older build of my ZFS pack is installed (I *really* need to tag & build a 0.8.0 egg of that...) that had a more primitive version of the TALES eval during a model, and liked to wreak havoc on shell `${variables}`. I later [changed the monkeypatch](https://github.com/daviswr/ZenPacks.daviswr.ZFS/commit/c169f46e8341307233586ab7089f173500d58f25) to use a regex that also looked for the /  and trailing } in the TALES expression to help. Going to guess that that's `zenoss.cmd.linux.ifconfig` or `zenoss.cmd.linux.interfaces` that it's causing to fail.

It might not be doing any ZFS monitoring, but with the pack installed, the monkeypatch is still loaded and active even for targets not using the ZFS modeler. Kinda sucks. I've got some new ideas for the sudo/pfexec/nothing solution for that, based on this smartctl pack. I'd recommend removing the ZFS pack if it's not needed on that box, or pull the latest from here and reinstall.

I've opened [an issue](https://github.com/daviswr/ZenPacks.daviswr.ZFS/issues/11) on the ZFS pack to come up with something better over there.

**Comment by sempervictus** [comment]
Thanks for the update, will update ZFS pack on that host.

**Comment by sempervictus** [comment]
Still getting these at the current revision, now they look like:
```
datasource | smartctl
-- | --
manager | 2f0d3537933b
resolution | Could  not create a command to send to zencommand because TALES evaluation  failed.  The most likely cause is unescaped special characters in the  command. eg $ or %
tb_exception | 'SmartctlPath'
template | SMART
```
The host in question here seems more or less normal:
```
[root@somehostname ~]# smartctl --scan
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/bus/0 -d megaraid,0 # /dev/bus/0 [megaraid_disk_00], SCSI device
/dev/bus/0 -d megaraid,1 # /dev/bus/0 [megaraid_disk_01], SCSI device
/dev/bus/0 -d megaraid,2 # /dev/bus/0 [megaraid_disk_02], SCSI device
```
RAID5 array made of commercial-grade SSDs on a magaraid

**Comment by daviswr** [comment]
Try remodeling? SmartctlPath and PrivEscCmd are new attributes and it might not have picked them up since getting the new perf template.

Though they should default to "smartctl" and "" if not modeled. Hm.

**Comment by sempervictus** [comment]
gotcha, lets see how it cycles. Thanks

**Comment by sempervictus** [comment]
Not seeing those attributes:
![image](https://user-images.githubusercontent.com/1331084/143725025-de12ea5e-45d7-4154-9fae-3d84dd0b2d0d.png)
Might need to reinstall again - something's not right here. ... "kids, don't beta test on prod kit"

**Comment by sempervictus** [comment]
More fun during removal, this is on zenoss6:
```
ERROR:zen.ZenPackCMD:Error removing ZenPack ZenPacks.daviswr.SMART
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 921, in RemoveZenPack
    transaction.commit()
  File "/opt/zenoss/lib/python2.7/site-packages/transaction/_manager.py", line 131, in commit
    return self.get().commit()
  File "/opt/zenoss/lib/python2.7/site-packages/transaction/_transaction.py", line 310, in commit
    reraise(t, v, tb)
  File "/opt/zenoss/lib/python2.7/site-packages/transaction/_transaction.py", line 301, in commit
    self._commitResources()
  File "/opt/zenoss/lib/python2.7/site-packages/transaction/_transaction.py", line 446, in _commitResources
    reraise(t, v, tb)
  File "/opt/zenoss/lib/python2.7/site-packages/transaction/_transaction.py", line 423, in _commitResources
    rm.tpc_vote(self)
  File "/opt/zenoss/lib/python2.7/site-packages/ZODB/Connection.py", line 797, in tpc_vote
    s = vote(transaction)
  File "/opt/zenoss/lib/python2.7/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "/opt/zenoss/lib/python2.7/site-packages/relstorage/storage.py", line 953, in tpc_vote
    resolved_by_vote = self._vote()
  File "/opt/zenoss/lib/python2.7/site-packages/relstorage/storage.py", line 1003, in _vote
    resolved_serials = self._finish_store()
  File "/opt/zenoss/lib/python2.7/site-packages/relstorage/storage.py", line 919, in _finish_store
    rdata = self.tryToResolveConflict(oid, prev_tid, serial, data)
  File "/opt/zenoss/lib/python2.7/site-packages/ZODB/ConflictResolution.py", line 299, in tryToResolveConflict
    data=newpickle)
ConflictError: database conflict error (oid 0x01c055, class Products.ZenModel.Device.Device, serial this txn started with 0x03e47067fee36000 2021-11-28 01:11:59.739418, serial currently committed 0x03e4706958aa4377 2021-11-28 01:13:20.780881)
```

**Comment by sempervictus** [comment]
When the going gets tough, the lazy get to brute-forcing, and what do you know...? it works!
Had to catch it when it wasn't modeling something apparently.

**Comment by daviswr** [comment]
I've seen the db conflict error message crop up on occasion, usually completely unrelated to what's going on, and a second try sorts it. Thinking odd currency issues with Zope but I've not actually looked into it.

The SmartctlPath and PrivEscCmd attributes are on the components and are populated by the modeler, rather than zProperties.

**Comment by sempervictus** [comment]
Ah, thanks. Reinstall does seem to make the TALES error stop... so far anyway, letting it cycle overnight.

**Comment by sempervictus** [comment]
Interesting, the events for reallocations no longer have a link to the drive having the issue, instead showing the serial number. Serial numbers are better identifiers for sure, but can they retain the link to the drive as before?
![image](https://user-images.githubusercontent.com/1331084/143725997-1be3370d-2f08-4c7e-be17-33dba14d284a.png)

**Comment by daviswr** [comment]
Try a remodel. Sounds like the components' IDs are stale, pre-serial dedupe change, but the events (seems like ones coming out of the parser directly rather than thresholds in the perf template) are using serial as the ID. Not having component IDs that match, it's just showing the ID string the event was generated against, rather than a matching component title.

**Comment by sempervictus** [comment]
Yup, thanks, that did it.

**Comment by daviswr** [comment]
Good to know. Sorry about all the headache here, I should've just made the serial numbers IDs to start with. But hopefully there'll only be these particular growing pains once...

**Comment by sempervictus** [comment]
No problem whatsoever - this has been a massively missing piece of the Zenoss ecosystem for ages, thanks so much for implementing it and in such detail.

**Comment by sempervictus** [comment]
So i'm still seeing a bunch of TALES errors, but the systems which have disks in them _are_ reporting, graphing, etc.
I'm not sure what's breaking functionally, but i think it bears tracking-down as once this is deemed "production-ready," people will depend on it and missing data could damn someone to a bad fate.

**Comment by sempervictus** [comment]
This might be related:
```
Component: | zenmodeler
-- | --
Event Class: | /Cmd/Fail
Status: | New
Message: | The command $ZENOTHING; IFS=$(echo -en "\n\b"); smart_path=$(command -v smartctl); if [[ $smart_path != *smartctl ]]; then smart_path=$(whereis smartctl \| cut -d' ' -f2); fi; smart_opts="--badsum=ignore --nocheck=standby"; if [[ $(uname -s) == Darwin ]]; t
```
seems to be truncated though

**Comment by daviswr** [comment]
Does that event have any output from the attempted command from the modeler? The truncation might just be a limitation of the event's message field.
