### ISSUE TITLE
ZenPack can find non-existent drives

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#8]
Not sure what to make of this one:
![image](https://user-images.githubusercontent.com/1331084/141608372-e610c2a4-c628-448a-be8d-5ffaca6b277d.png)

All of the detected drives are correct, all of the `0` one have no equivalent in the system.

**Comment by sempervictus** [comment]
Interesting, happens with DAS systems too, with _many_ more false positives (i think they're echoes of real devices somehow):
![image](https://user-images.githubusercontent.com/1331084/141643242-ce8aa0e1-4d9b-4a6b-b913-ca982185e1d3.png)

**Comment by daviswr** [comment]
My initial thought is that those are things like a `/dev/bus/0` RAID controller where some indexed drives are behind.

If you look in the details for all those 0 components, can you confirm that the Device Path is the same/similar?

Hoping this just how issue #4 is manifesting.

**Comment by sempervictus** [comment]
I have almost no RAID hardware in my targets, pretty much all HBAs here. :-\

**Comment by sempervictus** [comment]
Unfortunately removing the errant entries doesnt fly - they come back.

**Comment by daviswr** [comment]
Pull the latest, remodel, and see if anything's better. 

Your smartctl examples have been really helpful since I don't have any SCSI/SAS gear around. Also, a friend has sent me a bunch of output from his various servers with SAS and NVMe that I'll be looking over.

**Comment by sempervictus** [comment]
Confirm, the `0` devices seem to stay down now. Cleaning up as i go, will watch for their return.

**Comment by daviswr** [comment]
Good to hear, I'll keep an eye out for an update.

**Comment by sempervictus** [comment]
megaraid devices now coming up in LUN mode on a host - excellent. BTW, the SMART status and health columns are empty all over.

**Comment by daviswr** [comment]
Hm, I would've thought status & health test indicators would've been fixed after e5f8bf305034d8e1c8d28808fe6a3c0dc45cf6de or ced07e346fb85123bbde0e600f660b767fd74e20 . Are the indicators gray?

Could you post `smartctl --info --health --quietmode=noserial` from a device whose status and health columns are empty?

**Comment by sempervictus** [comment]
This has been working for a few revisions now - closing as "fixed"
