### ISSUE TITLE
Feature request: display serial # to permit search in large systems

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#9]
Fun situation: host with a megaraid internal card and an LSI HBA for a 45-disk DAS. The megaraid disks _show up twice_ since they're on `/dev/bus/0` and `/dev/sdX`. If the serial #s were displayed, it would be much easier to filter them down in the SMART component view especially when getting alerts to deduplicate against the SN.

**Comment by sempervictus** [comment]
Addendum: would be cool of the zenpack deduplicated them itself too, showing the `/dev/bus/X` path in the `Name` column to the right of the `/dev/sdY` disk name. Serial numbers have to be unique, even on VMs, or Windows will defecate bricks in regards to uniqueness validation and licensing. OpenStack SN's are UUIDs for example.

**Comment by daviswr** [comment]
Can totally do serials in the grid display, no problem.

Been thinking about how I might go about processing results in the modeler to look for multiple entries with the same serial. It's a good idea and I want to come up with an elegant way to do it.

Is the information reported when querying `/dev/bus/0 -d megaraid,X` different from `/dev/sdX`?

**Comment by sempervictus** [comment]
From what i can see, yeah, same data.
Also looks like health and smart indicators are coming up now in zenoss 6

**Comment by daviswr** [comment]
Grid serials display - 1ae816f953097ad7ac8856413b32ed35126ea589

**Comment by daviswr** [comment]
Try out 00128b6332056bfe71652864493dd59b3ca9f3ff , first attempt at dedupe by serial. Component IDs have changed to serial numbers, your graphs will reset.

**Comment by sempervictus** [comment]
Pulling and building, thanks as always.
The ID reset will re-trip all of my alerts won't it? :)

**Comment by daviswr** [comment]
Yeeaaaah... probably :)

The commit right before this removes a few ultimately-unused attributes from the yaml definition. You'll want to remove the old pack before installing this build of it, just to make sure those get cleaned up appropriately.

**Comment by sempervictus** [comment]
Works now, thank you sir.
